# fly.toml app configuration file generated for trien-khai-phan-mem on 2025-08-05T21:33:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trien-khai-phan-mem'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy --schema=./prisma/schema.prisma'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
