name: CI/CD Build, Test, Deploy & Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy-fly:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build Next.js app
        run: npm run build

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker buildx build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t trien-khai-phan-mem:latest --load .

      # Nếu muốn push lên Docker Hub thì mở phần này:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag trien-khai-phan-mem:latest ngochung275/trien-khai-phan-mem:latest
          docker push ngochung275/trien-khai-phan-mem:latest

      # Deploy lên Fly.io
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --release-command-timeout 600
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}